=== Roma3214185/oop-labs/lab2/data/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Schema of the medicines catalogue. The root element is Medicine,
    it contains a list of drugs.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- ===================== Root element ===================== -->

    <xs:element name="Medicine" type="MedicineType">
        <xs:unique name="uniqueDrugName">
            <xs:selector xpath="drug"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>

    <!-- ===================== Complex types ===================== -->

    <xs:complexType name="MedicineType">
        <xs:sequence>
            <xs:element name="drug" type="DrugType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DrugType">
        <xs:sequence>
            <xs:element name="name" type="TitleType"/>
            <xs:element name="pharm" type="TitleType"/>
            <xs:element name="group" type="GroupType"/>
            <xs:element name="analogs" type="AnalogsType" minOccurs="0"/>
            <xs:element name="versions" type="VersionsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="DrugIdType" use="required"/>
        <xs:attribute name="prescription" type="xs:boolean"
                      default="false"/>
    </xs:complexType>

    <xs:complexType name="AnalogsType">
        <xs:sequence>
            <xs:element name="analog" type="TitleType"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VersionsType">
        <xs:sequence>
            <xs:element name="version" type="VersionType"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Version (form) of the drug, may have several producers. -->
    <xs:complexType name="VersionType">
        <xs:sequence>
            <xs:element name="producer" type="ProducerType"
                        maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="form" type="FormType" use="required"/>
    </xs:complexType>

    <xs:complexType name="ProducerType">
        <xs:sequence>
            <xs:element name="certificate" type="CertificateType"/>
            <xs:element name="package" type="PackageType"/>
            <xs:element name="dosage" type="DosageType"/>
        </xs:sequence>
        <xs:attribute name="name" type="TitleType" use="required"/>
    </xs:complexType>

    <xs:complexType name="CertificateType">
        <xs:sequence>
            <xs:element name="number" type="CertificateNumberType"/>
            <xs:element name="issueDate" type="xs:date"/>
            <xs:element name="expiryDate" type="xs:date"/>
            <xs:element name="registeredBy" type="TitleType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PackageType">
        <xs:sequence>
            <xs:element name="quantity" type="QuantityType"/>
            <xs:element name="price" type="PriceType"/>
        </xs:sequence>
        <xs:attribute name="type" type="PackKindType" use="required"/>
    </xs:complexType>

    <xs:complexType name="PriceType">
        <xs:simpleContent>
            <xs:extension base="PriceValueType">
                <xs:attribute name="currency" type="CurrencyType"
                              default="UAH"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="DosageType">
        <xs:sequence>
            <xs:element name="amount" type="AmountType"/>
            <xs:element name="perDay" type="PerDayType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AmountType">
        <xs:simpleContent>
            <xs:extension base="AmountValueType">
                <xs:attribute name="unit" type="DosageUnitType"
                              use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- ===================== Simple types ===================== -->

    <xs:simpleType name="DrugIdType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="drug-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TitleType">
        <xs:restriction base="xs:string">
            <xs:minLength value="2"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GroupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="antibiotics"/>
            <xs:enumeration value="analgesics"/>
            <xs:enumeration value="antipyretics"/>
            <xs:enumeration value="vitamins"/>
            <xs:enumeration value="antivirals"/>
            <xs:enumeration value="antihistamines"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FormType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tablets"/>
            <xs:enumeration value="capsules"/>
            <xs:enumeration value="powder"/>
            <xs:enumeration value="drops"/>
            <xs:enumeration value="syrup"/>
            <xs:enumeration value="injection"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Ukrainian registration certificate number, e.g. UA/1234/01/01 -->
    <xs:simpleType name="CertificateNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="UA/\d{4,5}/\d{2}/\d{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PackKindType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="blister"/>
            <xs:enumeration value="bottle"/>
            <xs:enumeration value="box"/>
            <xs:enumeration value="sachet"/>
            <xs:enumeration value="ampoule"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="QuantityType">
        <xs:restriction base="xs:positiveInteger">
            <xs:maxInclusive value="1000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PriceValueType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:maxInclusive value="100000"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CurrencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="UAH"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="AmountValueType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:maxInclusive value="5000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DosageUnitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mg"/>
            <xs:enumeration value="mcg"/>
            <xs:enumeration value="g"/>
            <xs:enumeration value="ml"/>
            <xs:enumeration value="drops"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PerDayType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Roma3214185/oop-labs/lab2/data/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<Medicine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="medicines.xsd">
    <drug id="drug-001" prescription="true">
        <name>Amoxil</name>
        <pharm>GlaxoSmithKline</pharm>
        <group>antibiotics</group>
        <analogs>
            <analog>Flemoxin Solutab</analog>
            <analog>Ospamox</analog>
        </analogs>
        <versions>
            <version form="tablets">
                <producer name="GlaxoSmithKline UK">
                    <certificate>
                        <number>UA/1001/01/01</number>
                        <issueDate>2021-03-15</issueDate>
                        <expiryDate>2026-03-15</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>20</quantity>
                        <price currency="UAH">185.40</price>
                    </package>
                    <dosage>
                        <amount unit="mg">500</amount>
                        <perDay>3</perDay>
                    </dosage>
                </producer>
                <producer name="Teva Pharmaceuticals">
                    <certificate>
                        <number>UA/1001/01/02</number>
                        <issueDate>2022-06-01</issueDate>
                        <expiryDate>2027-06-01</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>16</quantity>
                        <price currency="UAH">142.10</price>
                    </package>
                    <dosage>
                        <amount unit="mg">500</amount>
                        <perDay>3</perDay>
                    </dosage>
                </producer>
            </version>
            <version form="powder">
                <producer name="GlaxoSmithKline UK">
                    <certificate>
                        <number>UA/1001/02/01</number>
                        <issueDate>2021-03-15</issueDate>
                        <expiryDate>2026-03-15</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="bottle">
                        <quantity>1</quantity>
                        <price currency="UAH">121.00</price>
                    </package>
                    <dosage>
                        <amount unit="mg">250</amount>
                        <perDay>3</perDay>
                    </dosage>
                </producer>
            </version>
        </versions>
    </drug>
    <drug id="drug-002" prescription="true">
        <name>Sumamed</name>
        <pharm>Teva</pharm>
        <group>antibiotics</group>
        <analogs>
            <analog>Azithromycin</analog>
            <analog>Azitrox</analog>
        </analogs>
        <versions>
            <version form="capsules">
                <producer name="Pliva Hrvatska">
                    <certificate>
                        <number>UA/2034/01/01</number>
                        <issueDate>2020-09-10</issueDate>
                        <expiryDate>2025-09-10</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>6</quantity>
                        <price currency="UAH">256.75</price>
                    </package>
                    <dosage>
                        <amount unit="mg">250</amount>
                        <perDay>1</perDay>
                    </dosage>
                </producer>
            </version>
            <version form="tablets">
                <producer name="Pliva Hrvatska">
                    <certificate>
                        <number>UA/2034/02/01</number>
                        <issueDate>2020-09-10</issueDate>
                        <expiryDate>2025-09-10</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>3</quantity>
                        <price currency="UAH">298.30</price>
                    </package>
                    <dosage>
                        <amount unit="mg">500</amount>
                        <perDay>1</perDay>
                    </dosage>
                </producer>
            </version>
        </versions>
    </drug>
    <drug id="drug-003">
        <name>Nurofen</name>
        <pharm>Reckitt Benckiser</pharm>
        <group>analgesics</group>
        <analogs>
            <analog>Ibuprofen</analog>
            <analog>Ibuprom</analog>
            <analog>Brufen</analog>
        </analogs>
        <versions>
            <version form="tablets">
                <producer name="Reckitt Benckiser Healthcare">
                    <certificate>
                        <number>UA/3110/01/01</number>
                        <issueDate>2022-01-20</issueDate>
                        <expiryDate>2027-01-20</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>24</quantity>
                        <price currency="UAH">98.60</price>
                    </package>
                    <dosage>
                        <amount unit="mg">200</amount>
                        <perDay>3</perDay>
                    </dosage>
                </producer>
            </version>
            <version form="syrup">
                <producer name="Reckitt Benckiser Healthcare">
                    <certificate>
                        <number>UA/3110/02/01</number>
                        <issueDate>2022-01-20</issueDate>
                        <expiryDate>2027-01-20</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="bottle">
                        <quantity>1</quantity>
                        <price currency="UAH">134.20</price>
                    </package>
                    <dosage>
                        <amount unit="ml">5</amount>
                        <perDay>3</perDay>
                    </dosage>
                </producer>
            </version>
        </versions>
    </drug>
    <drug id="drug-004">
        <name>Paracetamol</name>
        <pharm>Darnytsia</pharm>
        <group>antipyretics</group>
        <analogs>
            <analog>Panadol</analog>
            <analog>Efferalgan</analog>
        </analogs>
        <versions>
            <version form="tablets">
                <producer name="Darnytsia">
                    <certificate>
                        <number>UA/0456/01/01</number>
                        <issueDate>2019-11-05</issueDate>
                        <expiryDate>2029-11-05</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>10</quantity>
                        <price currency="UAH">12.35</price>
                    </package>
                    <dosage>
                        <amount unit="mg">500</amount>
                        <perDay>4</perDay>
                    </dosage>
                </producer>
                <producer name="Zdorovye">
                    <certificate>
                        <number>UA/0456/01/02</number>
                        <issueDate>2021-04-12</issueDate>
                        <expiryDate>2026-04-12</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>20</quantity>
                        <price currency="UAH">18.90</price>
                    </package>
                    <dosage>
                        <amount unit="mg">500</amount>
                        <perDay>4</perDay>
                    </dosage>
                </producer>
            </version>
            <version form="powder">
                <producer name="Darnytsia">
                    <certificate>
                        <number>UA/0456/02/01</number>
                        <issueDate>2019-11-05</issueDate>
                        <expiryDate>2029-11-05</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="sachet">
                        <quantity>10</quantity>
                        <price currency="UAH">64.00</price>
                    </package>
                    <dosage>
                        <amount unit="g">1</amount>
                        <perDay>3</perDay>
                    </dosage>
                </producer>
            </version>
        </versions>
    </drug>
    <drug id="drug-005">
        <name>Aevit</name>
        <pharm>Kyiv Vitamin Plant</pharm>
        <group>vitamins</group>
        <versions>
            <version form="capsules">
                <producer name="Kyiv Vitamin Plant">
                    <certificate>
                        <number>UA/5678/01/01</number>
                        <issueDate>2023-02-28</issueDate>
                        <expiryDate>2028-02-28</expiryDate>
                        <registeredBy>Ministry of Health of Ukraine</registeredBy>
                    </certificate>
                    <package type="blister">
                        <quantity>20</quantity>
